dist: trusty
sudo: off
language: python
services:
  - docker
git:
  depth: false
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python-dev
install: 
  - pip install azdev -qq
cache: pip
jobs:
  include:
    - stage: precheck
      env: PURPOSE='Reject PRs to master'
      script: ./scripts/ci/reject_master_prs.sh
    - stage: precheck
      env: PURPOSE='PEP8 Check'
      script: ./scripts/ci/precheck_pep8.sh
      python: 3.6
    - stage: precheck
      env: PURPOSE='License/History/DocMap'
      script: ./scripts/ci/precheck_header.sh
      python: 3.6
    - stage: precheck
      env: PURPOSE='Dependency Check'
      script: ./scripts/dependency/check.sh
      python: 3.6
    - stage: unittest
      python: 3.6
      env: TOXENV=py36
      script: ./scripts/ci/unittest.sh
    - stage: unittest
      python: 2.7
      env: TOXENV=py27
      script: ./scripts/ci/unittest.sh
    - stage: verify
      env: PURPOSE='Azure CLI Linter'
      script: ./scripts/ci/verify_linter.sh
      python: 3.6
    - stage: verify
      env:
      - PURPOSE='Test Suite (latest)'
      - REDUCE_SDK='True'
      script: ./scripts/ci/run_tests.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='Test Suite (latest)'
      script: ./scripts/ci/run_tests.sh
      python: 2.7
    - stage: verify
      env:
      - PURPOSE='Test Suite (2017-03-09)'
      - REDUCE_SDK='True'
      - AZURE_CLI_TEST_TARGET_PROFILE='2017-03-09'
      script: ./scripts/ci/run_tests.sh
      python: 3.6
    - stage: verify
      env:
      - PURPOSE='Test Suite (2018-03-01)'
      - AZURE_CLI_TEST_TARGET_PROFILE='2018-03-01'
      script: ./scripts/ci/run_tests.sh
      python: 2.7
    - stage: verify
      script: ./scripts/ci/test_static.sh
      env: PURPOSE='Pylint Check'
      python: 2.7
    - stage: verify
      script: ./scripts/ci/test_profile_integration.sh
      env: PURPOSE='Profile Self-Test'
      python: 3.6
    - stage: verify
      script: ./scripts/ci/test_profile_integration.sh
      env: PURPOSE='Profile Self-Test'
      python: 2.7
    - stage: verify
      script: ./scripts/ci/test_perf.sh
      env: PURPOSE='Module Load Performance'
      python: 3.6
    - stage: verify
      script: ./scripts/ci/test_ref_doc.sh
      env: PURPOSE='Verify Ref Docs'
      python: 3.6
    - stage: verify
      env: PURPOSE='Load Extensions'
      script: ./scripts/ci/test_extensions.sh
      python: 3.6
    - stage: publish
      script: ./scripts/ci/publish.sh
      python: 3.6
      env: PURPOSE='Edge Build'
      if: branch = dev and type = push
    - stage: publish
      script: ./scripts/ci/build_droid.sh
      python: 3.6
      env: PURPOSE='Docker Build'
      if: repo = Azure/azure-cli and type = push
stages:
  - precheck
  - unittest
  - verify
  - publish